//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BILL()
        {
            this.BILLINFOes = new HashSet<BILLINFO>();
        }
    
        public int billID { get; set; }
        public System.DateTime checkIn { get; set; }
        public Nullable<System.DateTime> checkOut { get; set; }
        public int tableID { get; set; }
        public int billStatus { get; set; }
        public string username { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual TABLELIST TABLELIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILLINFO> BILLINFOes { get; set; }
    }
}
