//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILLINFO
    {
        public int billInfoID { get; set; }
        public int billID { get; set; }
        public int foodID { get; set; }
        public int count { get; set; }
    
        public virtual BILL BILL { get; set; }
        public virtual FOOD FOOD { get; set; }
    }
}
